services:
  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: ./
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend


  backend:
    build:
      dockerfile: ./docker/backend/Dockerfile
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - path: ./backend/.env
        required: true
    volumes:
      - ./backend:/app

    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./backend
    #       target: /app
    #     - action: rebuild
    #       path: ./backend/requirements.txt

