services:
  backend:
    build:
      dockerfile: ./docker/backend/Dockerfile
      context: ./
    ports:
      - "8000:8000"
    env_file:
      - path: ./backend/.env
        required: true
    # volumes:
    #   - ./backend:/app

    # develop:
    #   watch:
    #     - action: sync+restart
    #       path: ./backend
    #       target: /app
    #     - action: rebuild
    #       path: ./backend/requirements.txt

